site_name: Opti
site_url: https://basf.github.io/mopti
repo_name: basf/mopti
repo_url: https://github.com/basf/mopti

nav:
  - index.md
  - Install: install.md
  - Overview: overview.md
  - API Reference:
      - Problem: ref-problem.md
      - Parameter: ref-parameter.md
      - Objective: ref-objective.md
      - Constraint: ref-constraint.md
      - Model: ref-model.md
      - Metric: ref-metric.md
      - Sampling: ref-sampling.md
      - Tools: ref-tools.md
      - Test Problems: ref-problems.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

plugins:
  - search
  # https://mkdocstrings.github.io/
  - mkdocstrings:
      watch:  # watch for changes when serving locally
        - opti
      # handlers:
      #   python:
      #     rendering:
      #       show_root_heading: yes
      #       show_root_full_path: no

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition

extra_css:
  - stylesheets/style.css

extra_javascript:
  # math support, https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js